version: '3.8'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: okodit/infra_sp2
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static/
    ports:
      - "80:80"
    depends_on:
      - web
