# Generated by Django 3.0.5 on 2020-11-06 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201106_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10, 'Рейтинг не может быть выше 10')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
